// Generated by CoffeeScript 1.9.3
var currentLevel, renderer;

currentLevel = 0;

renderer = {
  code: function(code, language) {
    return "<programlisting language=\"" + language + "\"><![CDATA[" + code + "]]></programlisting>";
  },
  blockquote: function(quote) {
    return "<quote>" + quote + "</quote>";
  },
  html: function(html) {
    return this.code(html, 'html');
  },
  heading: function(text, level) {
    var section;
    section = '';
    if (level > currentLevel) {
      while (currentLevel < level) {
        section += '<section>';
        currentLevel++;
      }
    } else if (level < currentLevel) {
      while (currentLevel > level) {
        section += '</section>';
        currentLevel--;
      }
    } else {
      section += '</section><section>';
    }
    return section + ("<title>" + text + "</title>");
  },
  hr: function() {
    return '</section><section>';
  },
  list: function(body, ordered) {
    return "<itemizedlist>" + body + "</itemizedlist>";
  },
  listitem: function(text) {
    return "<listitem>" + text + "</listitem>";
  },
  paragraph: function(text) {
    return "<para>" + text + "</para>";
  },
  table: function(header, body) {
    return "<table><thead>" + header + "</thead><tbody>" + body + "</tbody></table>";
  },
  tablerow: function(content) {
    return "<row>" + content + "</row>";
  },
  tablecell: function(content, flags) {
    return "<entry>" + content + "</entry>";
  },
  strong: function(text) {
    return "<emphasis role=\"strong\">" + text + "</emphasis>";
  },
  em: function(text) {
    return "<emphasis>" + text + "</emphasis>";
  },
  codespan: function(code) {
    return "<code>" + code + "</code>";
  },
  br: function() {
    return '</para><para>';
  },
  del: function(text) {
    return "<emphasis role=\"del\">" + text + "</emphasis>";
  },
  link: function(href, title, text) {
    return "<ulink url=\"" + href + "\">" + text + "</ulink>";
  },
  image: function(href, title, text) {
    return "<imagedata fileref=\"" + href + "\"/>";
  }
};
